### ISSUE TITLE
api call more vine videos

### ISSUE THREAD

**Issue by chrism91** [starlock/vino#14]
where would one modify the size of the call to lower redundancy from refreshing each page?

somewhere within bootstrap.js?

**Comment by Phil-Dean** [comment]
I'm not sure what @chrism91 means, but the title  being "api call more vine videos " seems to be exactly what I'm looking for.

In Twitter, they have the since_id parameter to add to a get user data call.  In Instagram, they have a min_id parameter to add to a get user data call.  

How does one check for updates using the Vine API based off a former post id?

**Comment by hult** [comment]
@chrism91 Not sure i'm following you here. This is a Python SDK for the Vine API intended to be used on the backend.

@naed11 We know exactly the part of the Vine API that we've implemented here. If you find out, you're more than welcome to send a PR to make the implementation more exhaustive. :)

**Comment by Phil-Dean** [comment]
:tophat: OK, thanks.

**Comment by chrism91** [comment]
I was wondering if there was a way to display more like 60-100 videos at a time. Request a larger page of information for your app to display. I have gone another route with my data project, but I still wonder

**Comment by Phil-Dean** [comment]
@chrism91 Just use the pagination data, page #, that comes with each call, and build a bigger data set on your end.

**Comment by kilickaya** [comment]
Could you please make it more clearer? I also would like to retrieve more results for my search of a certain tag, for example "rafting". When I search for 

api.vineapp/tags/search/rafting

It only retrieves top-20 result. How can I get more results, aka, changing the pagination parameter? Should I add something like ../rafting?=2 to get results from the second page?

**Comment by Phil-Dean** [comment]
@kilickaya you need to read the data set coming back on the first request and locate the pagination meta data, and then using data->nextPage from the data set to append ?page=PageNum to the original request URL as a query string.
