### ISSUE TITLE
Vine send message

### ISSUE THREAD

**Issue by mapring0019** [starlock/vino#15]
Could you tell me, does vine have request to send message? And how to send message in vine?

**Comment by Almaral-Engineering** [comment]
Hi, how can I get the session-id of the header, I am trying to log in but the one that it's on the reference gives me 401 UNAUTHORIZED

**Comment by hult** [comment]
Vino comes with calls to the parts of the API we needed to build it. We unfortunately have no further insights in how their API works. Feel free to submit a pull request if you find out how to do it. :)
