### ISSUE TITLE
Get Post by ID and Searches with Spaces are not Working

### ISSUE THREAD

**Issue by adam-hanna** [starlock/vino#16]
FYI...

Get post by ID is not working:

```
GET https://api.vineapp.com/timelines/posts/<postid>
```

Neither are searches that use a space (URI encoded)

```
GET https://api.vineapp.com/timelines/tags/I%20AM%20AN%20EXAMPLE
```

**Comment by onerandomgig** [comment]
From the API, vine doesnt have tags with spaces in them. You will have to first call https://api.vineapp.com/tags/search/{{ URL Encoded Search Query}}. This will return all the hashtags that are matching the search param. You will then need to select a tag and then search for it.

Alternatively, you could also strip away all the spaces and then execute the search api. If there are any matching hashtags with that, you will get the results
