### ISSUE TITLE
Api always returning 400 BAD REQUEST when authenticating

### ISSUE THREAD

**Issue by hackaprende** [starlock/vino#17]
When I try make a post to https://api.vineapp.com/users/authenticate I always get a 400 BAD REQUEST:

{
code: 101
data: ""
success: false
error: "That username or password is incorrect."
}

I have tried with different emails and passwords, am I doing something wrong?

**Comment by hult** [comment]
Well, the error message seems to suggest you're not using valid username/password combinations (?).

**Comment by hackaprende** [comment]
The weird thing is I have tried with three different accounts and I get the same response. I am sure I am using the correct username/password.

**Comment by levantAJ** [comment]
Waiting for the answer :( Any solutions?

**Comment by hult** [comment]
I can't reproduce this, `Vine().login(username, password)` works just fine. Closing.
