### ISSUE TITLE
Pagination with more than 10 pages not working

### ISSUE THREAD

**Issue by kilickaya** [starlock/vino#19]
I would like to search for videos with more than 10 pages results, i.e: 27k results. However, when I set page_id to a number more than 10, it returns empty results.

Any workaround?

**Comment by hult** [comment]
You may get more results in total if you also specify a larger page size (the `size` argument).

**Comment by kilickaya** [comment]
The size argument is already set to maximum (100). I would appreciate help if there is a way to go beyond 10 pages for a search term (i.e: /posts/search/bieber?page=11&size=100) in Vine API?

**Comment by hult** [comment]
I guess if they wanted you to get more than 1,000 results, the mechanism would work just like you're suggesting. Therefore, it seems reasonable to believe they limit it.
