### ISSUE TITLE
Error 500 when doing a call to the API

### ISSUE THREAD

**Issue by l30n** [starlock/vino#21]
Doing a call with to the API gives me a error 500 from the server, my local it works fine

**Comment by hult** [comment]
How do you mean local? Do you run a local Vine server? :)

**Comment by l30n** [comment]
@hult what I mean is that I have the script working on my local machine, when I upload it on the server it returns an error 500

**Comment by hult** [comment]
Then I guess there must be something wrong with the setup of your server?

**Comment by l30n** [comment]
To get a 500 response?

**Comment by hult** [comment]
Well, if it works locally there can't be anything wrong with the code, right? Have you checked that you provide the correct login information (if you read it through environment variables, have you checked that the application can read them)?

Do you have the actual response that the 500 error comes with?

**Comment by l30n** [comment]
for example I'm running this cURL

curl 'https://api.vineapp.com/users/profiles/916596819805483008' \
-H 'User-Agent: com.vine.iphone/1.0.3 (unknown, iPhone OS 6.1.0, iPhone, Scale/2.000000)' \
-H 'Accept-Language: es-MX,es-ES;q=0.9,es;q=0.7,es-AR;q=0.6,es-CL;q=0.4,en-US;q=0.3,en;q=0.1' 

On the server of the script I get
![image](https://cloud.githubusercontent.com/assets/1891125/16050717/85fc0ffc-3211-11e6-9ee8-68cfc2a1740e.png)

But on another server that I had it brings me the data with the exact same cURL

![image](https://cloud.githubusercontent.com/assets/1891125/16050755/af83f808-3211-11e6-8b55-11de7983b657.png)

What I'm suspecting is that the server is being blocked.

**Comment by hult** [comment]
I'm sorry, but this is not a forum for questions about access to the Vine API.
