### ISSUE TITLE
"GET https://api.vineapp.com/users/profiles/<userid>" is now private

### ISSUE THREAD

**Issue by jerrydboonstra** [starlock/vino#22]
We used to be able to access `GET https://api.vineapp.com/users/profiles/<userid>` without authentication.  As of yesterday, that stopped and now we get 400 status and `{"code": 100, "data": "", "success": false, "error": "You must be logged in to perform this action."}`

Intended or a bug?

**Comment by tylerarnold** [comment]
well isn't Vine dead? I imagine the API's are dead too.

**Comment by hult** [comment]
I wouldn't know, I don't build the Vine APIs. :) It seems pretty clear from the error message that their intent is to require login, no?

**Comment by jerrydboonstra** [comment]
vine is not accepting new content but in their press release they said they will continue to support access to existing content. i guess this is a problem with this framework and the docs here dont specify which endpoints are auth required or not, so i see this is not a bug.

**Comment by jerrydboonstra** [comment]
lol "'not a problem with this framework" i meant to say.
